Twitter:
  APIKey: 
  APIKeySecret: 
  BearerToken: 
  AccessToken: 
  AccessTokenSecret: 
  
DataBase:
  DBName: mysql # 数据库名称
  Host: 
  Port: 3306 # 端口
  Username: # 用户名
  Password: # 密码
  Charset: utf8mb4 # 编码格式
  Timeout: 10 # 超时时长 单位秒
  MaximumConnections: 100 # 最大连接数
  MinimumConnections: 10 # 最小连接数
  IdleConnectionTimeout: 20 # 空闲连接超时时间

TimedTask:
  Period: 3600 # 定时任务运行周期 单位: s

Limiter: # 表示 900秒内25个请求
  Duration: 900 # 时长 单位: s
  Quantity: 25 # 次数 单位: 个

Proxy: # 代理
  Host: 127.0.0.1 # 主机
  Port: 7890 # 端口